### ISSUE TITLE
[건의] 에러 문장 수정

### ISSUE THREAD

**Issue by mikekang47** [MessyParty/GlimsServer#12]
기존의 에러 문장의 경우
`사용자를 찾을 수 없습니다.` 처럼 한글로만 이루어진 평문으로 되어 있습니다.

이렇게 사용할 시 log를 확인할 때 불편함이 초래될 것 같아서
`[ERROR] 사용자를 찾을 수 업습니다.`로 변경하길 건의합니다.

**Comment by wnsvy607** [comment]
GOOD
