### ISSUE TITLE
[Https] API 서버 NGINX 설치 건의

### ISSUE THREAD

**Issue by wnsvy607** [MessyParty/GlimsServer#32]
### What's problem?
- 서버에 ssl 인증서를 발급 받아 https를 적용할 필요가 있다.

### How to solve it?
- Certbot을 이용해 ssl 인증서를 무료로 발급 받을 수 있다.  
- Nginx를 설치해 ssl 인증서 관리, 갱신을 간편하게 하고, WAS와의 역할을 분리한다. 
- API 서버는 8080 포트로 열고 Nginx의 리버스 프록시를 통해 외부와의 접근을 허용한다.

**Comment by mikekang47** [comment]
LGTM

**Comment by wnsvy607** [comment]
GOOD
